[package]
name = "utu_relay"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.9.2"
openzeppelin = "0.20.0"
utils = { git = "https://github.com/keep-starknet-strange/raito.git", rev = "dc3d54e84118630efa5e7069eb5c414fd8fbae3f" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.34.0" }

[scripts]
test = "snforge test"

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true

[lib]
sierra = true
casm = false

[cairo]
sierra-replace-ids = true
