[package]
name = "utu_relay"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.8.4"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.31.0" }

[scripts]
test = "snforge test"

[[target.starknet-contract]]
casm = true
sierra = true
