[package]
name = "utu_relay"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.11.4"
openzeppelin_access = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v2.0.0" }
openzeppelin_upgrades = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v2.0.0" }
utils = { git = "https://github.com/keep-starknet-strange/raito.git" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git" }

[scripts]
test = "snforge test"

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true

[lib]
sierra = true
casm = false

[cairo]
sierra-replace-ids = true
